### ISSUE TITLE
Autenticazione SPID

### ISSUE THREAD

**Issue by giafar** [pdavide/wai-portal#446]
@pdavide & @Valair Apro questa issue per la questione del cookie che cambia perchè, da una prima analisi, *non* mi sembra infrastrutturale.
Quello che succede è che la richiesta a https://webanalytics.italia.it invia correttamente il response header 
```
set-cookie: web_analytics_italia_session=eyJpdiI6IjdkbllqUFNoaU9ZSWU0eGhhSHY3blE9PSIsInZhbHVlIjoiQytxRm5cLzAwSVg4OEg4UmhGYnkxTit6ajJ1Y3RFVVFYUFlOQ2xWdnVUd0RHUkd4NHNHYVN4dmdoeXBZT3haQU0iLCJtYWMiOiJiMjEzZjYxY2Y0ZWI3Yzg4MGZiNTExZTkyZWMyNjk0ZWNkYzg0MTQ1OWM3NmQ2YmU3NjhhNmE5NDc2NWY2Y2UzIn0%3D; expires=Fri, 10-Jan-2020 22:54:19 GMT; Max-Age=7200; path=/; secure; httponly; samesite=strict
```
ma la successiva richiesta a https://webanalytics.italia.it/spid/providers, iniziata da uno script [js](https://webanalytics.italia.it/vendor/spid-auth/js/agid-spid-enter.min.latest.js), si comporta in modo *strano* ovvero invia correttamente il cookie nella request
```
cookie: web_analytics_italia_session=eyJpdiI6IjdkbllqUFNoaU9ZSWU0eGhhSHY3blE9PSIsInZhbHVlIjoiQytxRm5cLzAwSVg4OEg4UmhGYnkxTit6ajJ1Y3RFVVFYUFlOQ2xWdnVUd0RHUkd4NHNHYVN4dmdoeXBZT3haQU0iLCJtYWMiOiJiMjEzZjYxY2Y0ZWI3Yzg4MGZiNTExZTkyZWMyNjk0ZWNkYzg0MTQ1OWM3NmQ2YmU3NjhhNmE5NDc2NWY2Y2UzIn0%3D
```
ma in risposta invia un secondo set cookie differente dal precedente ovvero
```
set-cookie: web_analytics_italia_session=eyJpdiI6IjBBWVloZmxEcHZ5emo1NTF4dG9kdUE9PSIsInZhbHVlIjoiXC9cL1VyN08yRmhXbEZHb1dKSjkrSndyR0Jva1g1M084UUhzdk5Xa1NUQzFyaTlOOTRWNHR0TVU4M3l5eTBna3MyIiwibWFjIjoiNDgzZTIzMGJlZjVlNThjYWFhOGZlZjdlYjE1MTI5ZDlhNzMyNjcyYjMxZmY1MzgzM2UyNDU3NGUyOThiY2MyZiJ9; expires=Fri, 10-Jan-2020 22:54:19 GMT; Max-Age=7200; path=/; secure; httponly; samesite=strict
```
Fatto click sul bottone spid e selezionato il provider viene chiamata https://webanalytics.italia.it/spid/login che a sua volta manda il cookie
```
cookie: _pk_testcookie.1.30d9=1; web_analytics_italia_session=eyJpdiI6IjBBWVloZmxEcHZ5emo1NTF4dG9kdUE9PSIsInZhbHVlIjoiXC9cL1VyN08yRmhXbEZHb1dKSjkrSndyR0Jva1g1M084UUhzdk5Xa1NUQzFyaTlOOTRWNHR0TVU4M3l5eTBna3MyIiwibWFjIjoiNDgzZTIzMGJlZjVlNThjYWFhOGZlZjdlYjE1MTI5ZDlhNzMyNjcyYjMxZmY1MzgzM2UyNDU3NGUyOThiY2MyZiJ9
```
che risponde con un http status code 302, redirect verso idp, ma imposta un ulteriore cookie
```
set-cookie: web_analytics_italia_session=eyJpdiI6ImcwVCtBdzkwcWF4N1lROGVZenBIMUE9PSIsInZhbHVlIjoiRGtXV2ZoVGhTXC9TVE1qNWt6VXFnS3VQcHBFSkhXU001RDE2SDlDQU81Y0JsT1wvS1wvbXppUTRJT3VvSWF4OXlrRSIsIm1hYyI6ImEwNDY1MTVhYzkyZGVkMDI4NTYwNGUyNzE4MzZkMzA1OGEyNDBiY2ZjMTIyZTExYmVkOGVhYjQwMGVjYzcxYjcifQ%3D%3D; expires=Fri, 10-Jan-2020 23:05:58 GMT; Max-Age=7200; path=/; secure; httponly; samesite=strict
```

Senza tediarvi con questi cambi continui è evidente che al ritorno non ci sia più nulla da verificare: una prova fatta con @Valair è stata quella di scalere i pod del portale ad uno in modo da simulare una condizione *statefull* ma il comportamento è il medesimo.

Avete suggerimenti ?

**Comment by giafar** [comment]
Altra prova fatta è quella di abilitare il comando redis *FLUSHDB*, disabilitato di default, e svuotare il database 2 ma il risultato è stato lo stesso.

**Comment by pdavide** [comment]
Ho scoperto che:
- il cambio del valore del cookie ad ogni request/response è normale e non influisce sulla sessione
- il parametro `samesite=strict` dei cookie impedisce il funzionamento dell'autenticazione SAML

Approfondisco un po' meglio domani e preparo una PR.

**Comment by Valair** [comment]
Ciao @pdavide , mi sembra di capire che il flag `SameSite` `strict`, come scrivevi, non sia compatibile, con il `SAML POST binding` in quanto la risposta è vista come Cross-Origin; Google ha previsto un cambio di policy sulla gestione di quel flag in `Chrome 80` e si trovano diverse issue in merito:
- https://auth0.com/docs/sessions/concepts/cookie-attributes
- https://wiki.resolution.de/doc/saml-sso/latest/all/knowledgebase-articles/technical/impact-of-the-upcoming-changes-to-the-samesite-cookie-flag-default-behavior-in-chrome

**Comment by pdavide** [comment]
Si ho visto, infatti sto pensando ad una soluzione da integrare in spid-laravel che sia indipendente dalla sessione.

**Comment by pdavide** [comment]
La [versione 0.10.0 di spid-laravel](https://github.com/italia/spid-laravel/releases/tag/v0.10.0-beta) permette di usare il valore `lax` per il parametro `samesite` nel cookie di sessione.
